site_name: Cloud Scripting
site_url: /
#use_directory_urls: true
#use_absolute_urls: true
include_search: true

theme: readthedocs

pages:
- [index.md, Home]
- [use-cases.md, Use Cases]
- [cloud-events.md, Cloud Events]