site_name: Cloud Scripting
site_url: /
copyright: Copyright &copy; 2015, Jelastic, Inc.

#use_directory_urls: true
use_absolute_urls: true
include_search: true
theme_center_lead: false

#theme: readthedocs
theme_dir: './theme/readthedocs'
#theme: slate
#theme: highlight.js

markdown_extensions: [admonition, toc, tables]
                      #attention
                      #caution
                      #danger
                      #error
                      #hint
                      #important
                      #note
                      #tip
                      #warning

pages:
- ['index.md', 'Overview']

- ['quick-start.md', 'Quick Start']

# Creating Templates
- ['creating-templates/template-basics.md', 'Creating Templates', 'Template Basics']
- ['creating-templates/app-workflow.md', 'Creating Templates', 'Application Workflow']
- ['creating-templates/extention-workflow.md', 'Creating Templates', 'Extention Workflow']
- ['creating-templates/multi-language-scripting.md', 'Creating Templates', 'Multi-Language Scripting']

# Reference
- ['reference/actions.md', 'Reference', 'Actions']
#- ['reference/actions/execute-shell-commands.md', 'Reference', '&nbsp;&nbsp;&nbsp;&nbsp;&blacksquare;&nbsp; ExecuteShellCommands']
- ['reference/events.md', 'Reference', 'Events']
- ['reference/placeholders.md', 'Reference', 'Placeholders']
- ['reference/procedures.md', 'Reference', 'Procedures']

# Use Cases
- ['use-cases/vertical-scaling.md', 'Use Cases', 'Vertical Scaling']
- ['use-cases/horizontal-scaling.md', 'Use Cases', 'Horizontal Scaling']
- ['use-cases/docker-orchestration.md', 'Use Cases', 'Docker Orhestration']

# Examples
- ['examples/wordpress-cluster.md', 'Examples', 'Wordpress Cluster']


