site_name: Cloud Scripting
site_url: http://
copyright: Copyright &copy; 2015, Jelastic, Inc.

use_absolute_urls: true
include_search: true
theme_center_lead: false

theme_dir: './theme/readthedocs'

markdown_extensions: [admonition, toc, tables]

pages:
- Overview: index.md

- Quick Start: quick-start.md

- Jelastic & CS correspondence: jelastic-cs-correspondence.md

- Creating Templates:
   - Template Basics: creating-templates/template-basics.md
   - Writing Scripts: creating-templates/writing-scripts.md
   - Selecting Containers For Your Actions: creating-templates/selecting-containers.md
   - Getting User Input: creating-templates/user-input-parameters.md

- Troubleshooting: troubleshooting.md

- Reference:
   - Actions: reference/actions.md
   - Events: reference/events.md
   - Procedures: reference/procedures.md
   - Placeholders: reference/placeholders.md
   - Container Types: reference/container-types.md

- Examples:
   - Vertical Scaling: examples/vertical-scaling.md
   - Horizontal Scaling: examples/horizontal-scaling.md
   - Using Docker&reg;: examples/using-docker.md
   - Wordpress Cluster: examples/wordpress-cluster.md
   - Migration&Cloning Environment: examples/environment-migration-after-cloning.md
   - Two Envs in defferent regions: examples/two-envs-in-diff-regions.md

versions:
   releases:
      - 0.9
      - 0.8
      - 0.5

