version: "3"

tasks:
  serve:
    desc: "Start the development server"
    cmds:
      - pipenv run mkdocs serve

  build:
    desc: "Build the current version of the documentation"
    cmds:
      - pipenv run mkdocs build

  build-all:
    desc: "Build all versions described in the mkdocs.yml"
    cmds:
      - DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
        VERSION=$1;

        pipenv run mkdocs_versioned --default-branch=$VERSION;
        cp issue_report.php site/;
